var charProto = {
    x: 0,
    y: 0,
    z: 0,
    height: 10,
    width: 10,
    xVel: 0,
    xAccel: 0.9,
    maxXVel: 1,
    yVel: 0,
    stock: 3,
    weight: 100,
    percentage: 0,
    isHit: false,
    hitFrames: 2,
    canBeHit: true,
    movingR: false,
    movingL: false,
    jumping: false,
    facingR: false,
    facingL: false,
    hitBoxEnabled: false,
    addedHitBox: false,
    canJump: true,
    jumpCt: 0,
    maxJumpCt: 2,
    jumpSpeed: 1.8,
    jumpDur: 18,
    walkSpeed: 1,
    onGround: true,
    minDown: -100,
    minLeft: -100,
    minRight: 100,
    minUp: 100,
    boxBelow: undefined,
    boxAbove: undefined,
    boxLeft: undefined,
    boxRight:undefined,
    canBasicAttack: true,
    basicAttackFrames: 25,
    isRecover: false,
    canRecover: true,
    recoverFrames: 25,
    recoverVel: 3.3,
    walkStyle1: true,
    walkStyle2: false,
    walkStyle3: false,
    canMove: false,
    otherPlayer: undefined,
    grabLedgeTimer: 100,
    isGrabLedge: false,
    grabTimer: 100,
    isGrab: false,
    attackbbox: undefined,
    hitbbox: undefined,
    isRecoiling : false,
    recoilFrameDefault : 12,
    recoilFrames : 0
}
