var stageProto = {
    player1: undefined,
    player1Mesh: undefined,
    player1HitBoxMesh: undefined,
    player2: undefined,
    player2Mesh: undefined,
    player2HitBoxMesh: undefined,
    players: [],
    basicBoxAMesh: undefined,
    basicHitBoxAMesh: undefined,
    blockB: undefined,
    gravity: -0.75,
    scene: undefined,
    minimumY: -40,
    maximumY: 180,
    minimumX: -200,
    maximumX: 200,
    height: 0,
    width: 0,
    airResistance: 0,
    stageHitBoxes: [],
    stageBlocks:  [],
    blockAMeshes: [],
    timer: 0,
    timerIncrement: 0,
    maxTime: 120,
    skyBoxURL: ""
}
